version: '2.1'

services:
  devops:
    container_name: devops
    image: anmolnagpal/devops-machine:0.0.1
    mem_limit: 3g
    memswap_limit: 3g
    cpu_shares: 30
    privileged: true
    ports:
      - "1310:22" # ssh
    volumes:
      - ./bin/devops:/image/
      - ~/Workspace/data/log:/var/log/
      - ./bin/devops/etc/zshrc:/home/ubuntu/.zshrc
      - ./bin/devops/etc/zsh/aliases.conf:/home/ubuntu/.aliases
      - ./bin/devops/etc/zsh/extra.conf:/home/ubuntu/.extra
      - ~/Workspace:/home/ubuntu/workspace
      - ~/.ssh:/home/ubuntu/.ssh
      - ~/.aws:/home/ubuntu/.aws
      - ~/.zsh_history:/home/ubuntu/.zsh_history
      - ~/.gitconfig:/home/ubuntu/.gitconfig
    networks:
      dev_net_devops:
        ipv4_address: 10.13.0.13

networks:
  dev_net_devops:
    driver: bridge
    ipam:
     config:
       - subnet: 10.13.0.0/16
         gateway: 10.13.0.1


